### ISSUE TITLE
HTTP version?

### ISSUE THREAD

**Issue by andrevidela** [kbertalan/tyttp#1]
I just noticed that we do not have access to the HTTP version from the `Request` record, is it available anywhere?

**Comment by kbertalan** [comment]
No, it is missing from the request.
However at the current stage only HTTP 1.x is available, because this node API is used: https://nodejs.org/docs/latest-v14.x/api/http.html
You can assume that you see HTTP 1.1 requests when you use tyttp.

For supporting HTTP2 this API need to be adapted into tyttp: https://nodejs.org/docs/latest-v14.x/api/http2.html

**Comment by kbertalan** [comment]
@andrevidela can you please check this PR? Does it match your expectation?
https://github.com/kbertalan/tyttp/pull/2
