### ISSUE TITLE
How to make HTTP requests while handing incoming requests

### ISSUE THREAD

**Issue by alexhumphreys** [kbertalan/tyttp#3]
I'm trying to build off the [Files.idr](https://github.com/kbertalan/tyttp/blob/main/tests/server/files/Files.idr) example, and  just wondering, any idea how while handling a http request, i can make an http request, then use that while responding?
I know in javascript this would involve some kind of promises/callbacks/bind, but i can't work out how that would translate to tyttp. 
I'm trying something like this:
```
extraReq :
  Error e
  => HasIO io
  => Context me u v h1 s StringHeaders a b
  -> io $ Context me u v h1 Status StringHeaders a (Publisher IO e Buffer)
extraReq ctx = do
  putStrLn "extraReq"
  https <- requireHTTPS
  x <- getHttps https "https://jsonplaceholder.typicode.com/todos/1" $ \res => do
        putStrLn res.statusCode
        onData res putStrLn
        -- TODO somehow use this when responding to calls to /extraReq
  text "extraReq" ctx >>= status OK
```
The `getHttps` is pretty much the same as your `HTTP.get`. You can [find the full file here](https://github.com/alexhumphreys/dummy-server/blob/8df609a0e7336474d714fd8649d0c41d2fa4423a/Main.idr#L47). Ideally the `text "extraReq" ctx >>= status OK` would be nested where the TODO is.

Not sure i'm explaining this well, so let me know if you need more details.

**Comment by kbertalan** [comment]
I have created a branch and a PR which shows an example how to do that. The main thing is at https://github.com/kbertalan/tyttp/blob/a34f56c0515fa5effe1adcbbbb8afa9aaf7e669b/src/Main.idr#L33-L41

The explanation is that the best way to do this is to manually create a `Publisher IO e Buffer` which is initiating the outgoing https request and handles the callbacks of the https response. The response has `onData` and `onEnd` callbacks, where we have to pass the incoming response to the outgoing response stream's subscriber, ie: `onNext` and `onSucceded` callbacks.

This way you will properly handle the situation when the https client response triggers multiple 'data' event.

If you want further processing the https response, then you first need to collect the received data from possibly multiple 'data' events, then process and send the data in a singleton stream (`TyTTP.Core.Stream.singleton` which is a single `onNext` and a single `onSucceded` call).

Just a quick disclaimer, I have included the Node.HTTP.Client package into TyTTP in order to quickly test the TyTTP server. This is the main reason it has no proper integration with `TyTTP.Core.Stream`, and it has an interface which is closer to the original nodejs API.

**Comment by alexhumphreys** [comment]
Thanks for the fast response, this looks great! 

I appreciate the explanation too, I'll try play about with this example :)

**Comment by kbertalan** [comment]
I missed to include headers and possible error cases.
Let me know if you are interested in those, and I can extend this example.

Also note, that the above PR contains a bug fix, which is needed for the example to work.

**Comment by alexhumphreys** [comment]
I think I got how the headers would work, but would be interested in the error example. I think it'd be something like this:
```
{ response.status := OK
, response.headers := [("X-foo", "bar")]
, response.body := MkPublisher $ \s => do
  putStrLn "Calling http"
  ignore $ http.get "http://localhost:3000/doesnotexist?q=from-request" $ \res => do
                      putStrLn "Got response"
                      onData res s.onNext
                      onEnd res s.onSucceded
                      onError res s.onFailed
} ctx
```
but I might be wrong, and I'm not sure how to set the `response.status` based on the inner request...

**Comment by kbertalan** [comment]
> I'm not sure how to set the `response.status` based on the inner request...

That is a little more complicated, as first we have to initiate the http client request from the Promise, then when it succeeds we have the response, which then can be passed to the Stream.

I am not sure if this information is enough for you though.

**Comment by alexhumphreys** [comment]
It's not, but it's also already more than enough information for me to handle/play about with at the moment, so it's all good 😅 Thanks for the help!

**Comment by kbertalan** [comment]
I have updated the example again (and found another bug around http clients)

https://github.com/kbertalan/tyttp/blob/8aa07dc8f9921bf714e7df442c37eccfae3a5f41/src/Main.idr#L30-L46

This shows how to initate the http call from the Promise monad, then use the response in the response.body.

I would like to highlight that I had to add the `:>` operator to this route, as the original type is a `Promise` wrapped into a `MaybeT` (because of the `route'` which uses `MaybeT` for selecting the first matching route). The `:>` actually is a hidden `lift` tailored for the TyTTP needs.

In addition, this example would hang forever if the HTTP request would fail with a JS exception, because the error handling of the HTTP client is not modelled correctly in `Node.HTTP.Client` module, and the example never calls `cb.onFailed "some error"`.

**Comment by kbertalan** [comment]
I will wait till you approve the PR, then the fixes will be available in main branch too.

**Comment by alexhumphreys** [comment]
Ah that's really cool, thanks! Thanks for highlighting the `:>` too, I would have missed that. I'm still a little unclear about the exact interactions of `Context`, `Publisher`, `Subscriber`, and `Promise`, but this definitely gets me a lot closer 👍

**Comment by kbertalan** [comment]
In short, the `HTTP.listen'` expects to have a handler with a type which can be considered as  `requestContext -> Promise responseContext`, as you can see below.
 
https://github.com/kbertalan/tyttp/blob/main/src/TyTTP/Adapter/Node/HTTP.idr#L107-L108

The request context has a stream of body modelled with `Publisher`, the response context has a stream of response body also modelled with a `Publisher`.
A `Publisher` executes all its effects when a code is calling its `subscribe` function with a `Subscriber`. A `Subscriber` is just the tripple of callbacks for receiving data (`onNext` - 0 or more times can be called), end of published data (`onSucceded` - only once, no other callbacks are called after it), or in error case (`onFailed` - only once, no other callbacks are called).

The `Promise` is similar, it executes its effects if there are two callbacks are provided to it (`onSucceded` and `onFailed`). The good thing is that `Promise` can be a monad, so we can use the `do` notation with it. (The same Promise can be found in other idris2 packages too, it is quite common.)

So when you pass a `requestContext -> Promise responseContext` to a `listen'` function, then you only specify the effects as a DSL. When there is a HTTP request, the `listen'` will create the `requestContext`, pass it to your function and 'subscribes' to the Promise, then the response body stream.

This means that you code runs only when the `listen'` pulls data from your function, which in turn executes the callbacks.

The `Promise` in the `requestContext -> Promise responseContext` type was needed to handle async effects during HTTP request processing. These async effects are usually NodeJS APIs with callbacks, JS Promises, or when I had to collect the request body from the stream into a single big buffer before parsing it as JSON and making idris2 records out of it.

And this type is now proved to be handy for calling external HTTP services in an async way.

**Comment by kbertalan** [comment]
As the PR is merged, I am now closing this issue. Any other conversation can be continued on discord.
